version: '3.8'
services:
  mongodb:
    container_name: mongodb
    restart: always 
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
  stock.api:
    container_name: stock.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://mongodb:27017
    ports:
      - "5011:80"
    depends_on:
      - mongodb
      